-- list all owners who have surname 'Smith', number of vehicles and number of offences they own (person_name, person_surname, num_vehicles_owned, num_offences_committed)
--SELECT
--    P.PERSON_NAME,
--    P.PERSON_SURNAME,
--    COUNT(DISTINCT VO.VEHICLE_OWNER_ID) AS NUM_VEHICLES_OWNED,
--    COUNT(DISTINCT O.OFFENSE_ID) AS NUM_OFFENCES_COMMITTED
--FROM
--    PERSON P
--    JOIN VEHICLE_OWNER VO
--        ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID
--    JOIN MOTOR_VEHICLE MV
--        ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID
--    LEFT JOIN OFFENSE O
--        ON O.OFFENSE_MOTOR_VEHICLE_ID = MV.MOTOR_VEHICLE_ID
--WHERE
--    P.PERSON_SURNAME = 'Smith'
--GROUP BY
--    P.PERSON_NAME,
--    P.PERSON_SURNAME;

EXPLAIN PLAN FOR
SELECT /*+ NO_INDEX(p IDX_PERSON_SURNAME) */
    P.PERSON_NAME,
    P.PERSON_SURNAME,
    COUNT(DISTINCT VO.VEHICLE_OWNER_ID) AS NUM_VEHICLES_OWNED,
    COUNT(DISTINCT O.OFFENSE_ID) AS NUM_OFFENCES_COMMITTED
FROM
    PERSON P
    JOIN VEHICLE_OWNER VO
        ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID
    JOIN MOTOR_VEHICLE MV
        ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID
    LEFT JOIN OFFENSE O
        ON O.OFFENSE_MOTOR_VEHICLE_ID = MV.MOTOR_VEHICLE_ID
WHERE
    P.PERSON_SURNAME = 'Smith'
GROUP BY
    P.PERSON_NAME,
    P.PERSON_SURNAME;
-- Print the plan
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX IDX_PERSON_SURNAME;
CREATE INDEX IDX_PERSON_SURNAME ON PERSON (PERSON_SURNAME);
EXPLAIN PLAN FOR
SELECT /*+ INDEX(P IDX_PERSON_SURNAME) */
    P.PERSON_NAME,
    P.PERSON_SURNAME,
    COUNT(DISTINCT VO.VEHICLE_OWNER_ID) AS NUM_VEHICLES_OWNED,
    COUNT(DISTINCT O.OFFENSE_ID) AS NUM_OFFENCES_COMMITTED
FROM
    PERSON P
    JOIN VEHICLE_OWNER VO
        ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID
    JOIN MOTOR_VEHICLE MV
        ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID
    LEFT JOIN OFFENSE O
        ON O.OFFENSE_MOTOR_VEHICLE_ID = MV.MOTOR_VEHICLE_ID
WHERE
    P.PERSON_SURNAME = 'Smith'
GROUP BY
    P.PERSON_NAME,
    P.PERSON_SURNAME;
-- Print the plan
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);