-- list all owners who have surname 'Smith' and number of vehicles they own (person_name, person_surname, num_vehicles_owned)
-- SELECT
--     P.PERSON_NAME,
--     P.PERSON_SURNAME,
--     COUNT(MV.MOTOR_VEHICLE_ID) AS NUM_VEHICLES_OWNED
-- FROM
--     PERSON        P
--     JOIN VEHICLE_OWNER VO
--     ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID JOIN MOTOR_VEHICLE MV
--     ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID
-- WHERE
--     P.PERSON_SURNAME = 'Smith'
-- GROUP BY
--     P.PERSON_NAME,
--     P.PERSON_SURNAME;
EXPLAIN PLAN FOR SELECT P.PERSON_NAME, P.PERSON_SURNAME, COUNT(MV.MOTOR_VEHICLE_ID) AS NUM_VEHICLES_OWNED FROM PERSON P JOIN VEHICLE_OWNER VO ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID JOIN MOTOR_VEHICLE MV ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID WHERE P.PERSON_SURNAME = 'Smith' GROUP BY P.PERSON_NAME, P.PERSON_SURNAME;

SELECT
    *
FROM
    TABLE( DBMS_XPLAN.DISPLAY());

DROP INDEX IDX_PERSON_SURNAME;

CREATE INDEX IDX_PERSON_SURNAME ON PERSON (
    PERSON_SURNAME
);

EXPLAIN PLAN FOR SELECT P.PERSON_NAME, P.PERSON_SURNAME, COUNT(MV.MOTOR_VEHICLE_ID) AS NUM_VEHICLES_OWNED FROM PERSON P JOIN VEHICLE_OWNER VO ON VO.VEHICLE_OWNER_PERSON_ID = P.PERSON_ID JOIN MOTOR_VEHICLE MV ON MV.MOTOR_VEHICLE_ID = VO.VEHICLE_OWNER_ID WHERE P.PERSON_SURNAME = 'Smith' GROUP BY P.PERSON_NAME, P.PERSON_SURNAME;

SELECT
    *
FROM
    TABLE( DBMS_XPLAN.DISPLAY());