--Tento trigger zkontroluje, zda je věk osoby v tabulce PERSON starší nebo roven 18 let a zda má povinnost mít řidičský průkaz podle zákona.
--Pokud některá z těchto podmínek není splněna, trigger zabrání vložení dalšího záznamu
CREATE OR REPLACE TRIGGER PERSON_AGE_LICENSE_TRIGGER BEFORE
    INSERT ON PERSON FOR EACH ROW
DECLARE
    MIN_DRIVING_AGE CONSTANT INT := 18;
BEGIN
    IF :NEW.PERSON_AGE < MIN_DRIVING_AGE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Person must be at least 18 years old or have a valid driver''s license.');
    END IF;
END;
/

--Tento trigger počítá počet osob, které jsou pojištěny u každé pojistné smlouvy v tabulce INSURANCE
--a aktualizuje sloupec INSURANCE_PERSON_COUNT v této tabulce
CREATE OR REPLACE TRIGGER PERSON_INSURANCE_COUNT_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF PERSON_INSURANCE_ID ON PERSON FOR EACH ROW
BEGIN
    UPDATE INSURANCE
    SET
        INSURANCE_PERSON_COUNT = INSURANCE_PERSON_COUNT + 1
    WHERE
        INSURANCE_ID = :NEW.PERSON_INSURANCE_ID;
    UPDATE INSURANCE
    SET
        INSURANCE_PERSON_COUNT = INSURANCE_PERSON_COUNT - 1
    WHERE
        INSURANCE_ID = :OLD.PERSON_INSURANCE_ID;
END;
/

CREATE OR REPLACE TRIGGER MOTOR_VEHICLE_INSURANCE_COUNT_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF MOTOR_VEHICLE_INSURANCE_ID ON MOTOR_VEHICLE FOR EACH ROW
BEGIN
    UPDATE INSURANCE
    SET
        INSURANCE_MOTOR_VEHICLE_COUNT = INSURANCE_MOTOR_VEHICLE_COUNT + 1
    WHERE
        INSURANCE_ID = :NEW.MOTOR_VEHICLE_INSURANCE_ID;
    UPDATE INSURANCE
    SET
        INSURANCE_MOTOR_VEHICLE_COUNT = INSURANCE_MOTOR_VEHICLE_COUNT - 1
    WHERE
        INSURANCE_ID = :OLD.MOTOR_VEHICLE_INSURANCE_ID;
END;
/