-- This trigger checks if the age of a person in the PERSON table is older than or equal to 18 years and if they are required to have a driver's license according to the law
-- If either of these conditions is not met, the trigger prevents the insertion of another record
CREATE OR REPLACE TRIGGER PERSON_AGE_LICENSE_TRIGGER BEFORE
    INSERT ON PERSON FOR EACH ROW
DECLARE
    MIN_DRIVING_AGE CONSTANT INT := 18;
BEGIN
    IF :NEW.PERSON_AGE < MIN_DRIVING_AGE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Person must be at least 18 years old or have a valid driver''s license.');
    END IF;
END;
/

-- This trigger counts the number of people insured under each insurance policy in the INSURANCE table and updates the INSURANCE_PERSON_COUNT column in this table
CREATE OR REPLACE TRIGGER PERSON_INSURANCE_COUNT_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF PERSON_INSURANCE_ID ON PERSON FOR EACH ROW
BEGIN
    UPDATE INSURANCE
    SET
        INSURANCE_PERSON_COUNT = INSURANCE_PERSON_COUNT + 1
    WHERE
        INSURANCE_ID = :NEW.PERSON_INSURANCE_ID;
    UPDATE INSURANCE
    SET
        INSURANCE_PERSON_COUNT = INSURANCE_PERSON_COUNT - 1
    WHERE
        INSURANCE_ID = :OLD.PERSON_INSURANCE_ID;
END;
/

CREATE OR REPLACE TRIGGER MOTOR_VEHICLE_INSURANCE_COUNT_TRIGGER AFTER
    INSERT OR DELETE OR UPDATE OF MOTOR_VEHICLE_INSURANCE_ID ON MOTOR_VEHICLE FOR EACH ROW
BEGIN
    UPDATE INSURANCE
    SET
        INSURANCE_MOTOR_VEHICLE_COUNT = INSURANCE_MOTOR_VEHICLE_COUNT + 1
    WHERE
        INSURANCE_ID = :NEW.MOTOR_VEHICLE_INSURANCE_ID;
    UPDATE INSURANCE
    SET
        INSURANCE_MOTOR_VEHICLE_COUNT = INSURANCE_MOTOR_VEHICLE_COUNT - 1
    WHERE
        INSURANCE_ID = :OLD.MOTOR_VEHICLE_INSURANCE_ID;
END;
/